[book]
authors = ["enterprise-network-engineer-guide contributors"]
language = "zh-CN"
src = "."
title = "企业网络工程师学习手册"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"

[output.pdf]

[output.epub]